### PR TITLE
Accept fdp2rdf endpoint through http request argument

### PR DESCRIPTION
**Pull request by liyakun**

### CODE REVIEW

**Comment by liyakun** [comment]
@akariv Do I need a password to run docker? Which seems to the the point where the test failed. Thanks.

**Comment by akariv** [comment]
No, tests had passed - it probably failed because you're trying to merge from a local `master` branch (which should be okay... @brew wdyt?)

**Comment by akariv** [comment]
@liyakun Do note that os-admin needs to be updated as well to support the new API (otherwise we can't merge this as it would break os-admin).
Do you think you could do the matching PR there as well?

**Comment by brew** [comment]
As the Docker credentials are available from .travis.yml as encrypted values, they won't be available to untrusted builds, e.g. pull requests from another repository: https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml

**Comment by liyakun** [comment]
@akariv I could work on the adaptation of os-admin, but as what I wrote in https://github.com/openspending/openspending/issues/1346, we need to agree on how should I adapt os-admin, maybe one of the followings could be performed:
1. Move **run_hook** from _os-admin_ to _os-packager_, and the fdp2rdf pipeline(if it is configured in _os-packager_) could be triggered after dataset is uploaded via _os-packager_. This requires some modification of _os-packager_ as well.
2. Change the **run_hook** part of _os-admin_ UI, to provide user the possibility to manually input one fdp2rdf url.
3. Just provide _os-admin_ with one default fdp2rdf url, this could be the solution which is the easiest to implement.

**Comment by liyakun** [comment]
@akariv As a temporary solution, I have implemented the third suggestion that was mentioned above, and created a [pull request](https://github.com/openspending/os-admin/pull/20) to os-admin.

**Comment by akariv** [comment]
@brew I meant why the docker build even runs on a non-master, PR build (same happens in the linked os-admin PR).
@liyakun - I also think that (3) is the preferred solution.

**Comment by brew** [comment]
@akariv Having a Docker build for PRs can be useful for testing on staging.

**Comment by akariv** [comment]
Sorry @brew, mistype: 'why the docker deploy (`make ci-push`) even runs on a non-master, PR build'

**Pull request merged**
